apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalog
  namespace: otel-demo
  annotations:
    predictive-kubernetes-scaling.observability-labs.dynatrace.com/uuid: 'e9bf678b-65d8-4da6-9f69-8834f651d84a'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-demo-productcatalogservice
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
