apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quote
  namespace: otel-demo
  annotations:
    predictive-kubernetes-scaling.observability-labs.dynatrace.com/uuid: '8a94171b-cf03-4ed3-9d18-fb2e260a80db'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-demo-quoteservice
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
