apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy_1_12.yaml
  - hpa-accounting.yaml
  - hpa-cartservice.yaml
  - hpa-adservice.yaml
  - hpa-checkout.yaml
  - hpa-currency.yaml
  - hpa-email.yaml
  - hpa-frontend.yaml
  - hpa-paymentservice.yaml
  - hpa-productcatalog.yaml
  - hpa-quote.yaml
  - hpa-recommendation.yaml
  - hpa-shipping.yaml

