apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: predictive-kubernetes-scaling-demo
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
