apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anomaly-simulation
  namespace: horizontal-scaling
  annotations:
    predictive-kubernetes-scaling.observability-labs.dynatrace.com/uuid: 'c4e9324f-312f-4a1c-9d32-c8288d73626b'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anomaly-simulation
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
