apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anomaly-simulation
  namespace: horizontal-scaling
  annotations:
    predictive-kubernetes-scaling.observability-labs.dynatrace.com/repo: 'KatharinaSick/obslab-predictive-kubernetes-scaling'
    predictive-kubernetes-scaling.observability-labs.dynatrace.com/path: 'apps/horizontal-scaling/hpa.yaml'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anomaly-simulation
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
