---
apiVersion: dynatrace.com/v1beta2
kind: DynaKube
metadata:
  name: predictive-kubernetes-scaling-demo
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
    feature.dynatrace.com/automatic-kubernetes-api-monitoring-cluster-name: "predictive-kubernetes-scaling-demo"
spec:
  apiUrl: https://DYNATRACE_LIVE_URL/api

  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring:
      useCSIDriver: true
      namespaceSelector:
        matchLabels:
          oneagent: "true"
  activeGate:
    capabilities:
      - kubernetes-monitoring
      - routing
      - metrics-ingest
      - dynatrace-api

    resources:
      requests:
        cpu: 5m
        memory: 51Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi