apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: predictive-kubernetes-scaling-demo
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  apiUrl: https://DYNATRACE_LIVE_URL/api
  oneAgent:
    cloudNativeFullStack:
      image: ""
  activeGate:
    capabilities:
      - kubernetes-monitoring
      - routing
      - metrics-ingest
      - dynatrace-api
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi