apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-connect-hpa-reader
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-connect-hpa-reader
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-connect-hpa-reader
roleRef:
  kind: ClusterRole
  name: edge-connect-hpa-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edge-connect-hpa-reader
    namespace: dynatrace
---
apiVersion: dynatrace.com/v1alpha2
kind: EdgeConnect
metadata:
  name: isitobservable-predectivescaling
  namespace: dynatrace
spec:
  apiServer: ktp91462.apps.dynatrace.com
  serviceAccountName: edge-connect-hpa-reader
  oauth:
    provisioner: true
    clientSecret: edge-connect-isitobservable-predectivescaling-credentials
    endpoint: https://sso.dynatrace.com/sso/oauth2/token
    resource: "urn:dtenvironment:ktp91462"
  kubernetesAutomation:
    enabled: true