apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-connect-hpa-reader
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-connect-hpa-reader
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-connect-hpa-reader
roleRef:
  kind: ClusterRole
  name: edge-connect-hpa-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edge-connect-hpa-reader
    namespace: dynatrace
---
apiVersion: dynatrace.com/v1alpha1
kind: EdgeConnect
metadata:
  name: CODESPACE_NAME-hpa-reader
  namespace: dynatrace
spec:
  apiServer: DYNATRACE_APPS_URL
  serviceAccountName: edge-connect-hpa-reader
  oauth:
    provisioner: true
    clientSecret: edge-connect-CODESPACE_NAME-hpa-reader-credentials
    endpoint: https://DYNATRACE_SSO_URL
    resource: "urn:dtenvironment:DYNATRACE_ENVIRONMENT_ID"
  kubernetesAutomation:
    enabled: true